# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
########################################
  ### RESOURCES: System Configuration
  ########################################
  resources:
    # Creates a new Dev Drive
    ### -------------------------------------
    - resource: Disk
      id: DevDrive1
      directives:
        module: StorageDsc
        allowPrerelease: true
      settings:
        DiskId: '0'
        DiskIdType: 'Number'
        DriveLetter: 'Z'
        FSLabel: 'Dev Drive 1'
        DevDrive: true
        AllowDestructive: true
        FSFormat: 'ReFS'
        Size: '50Gb'
    ### Install Git
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.Git
    ### Configure Git to use Default WAM account
    ### -------------------------------------
    - resource: PSDscResources/Script
      dependsOn:
        - git
      directives:
        description: Configure Git to use Default WAM account
      settings:
        SetScript: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
          SET GCM_MSAUTH_USEDEFAULTACCOUNT="true"
          git config --global credential.msauthUseDefaultAccount true
        GetScript: return $false
        TestScript: return $false
    ### Install Azd
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azd
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.Azd
    ### Install VSCode
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.Microsoft.VisualStudioCode