# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: DemoApp
version: 1.0.0
summary: Architecture for self contained App Service
description: Deploys app service plan, app service, and application Insights
runner: ARM
templatePath: main.json

parameters:
  - id: baseName
    name: Base Name for resources
    description: 'Name of the service'
    type: string
    required: true
  - id: location
    name: Location for Resources
    description: 'Location to deploy new resources into default is eastus'
    type: string
    required: false
  - id: logAnalyticsResourceGroup
    name: Resource Group for Log Analytics
    description: 'The Resource Group the existing Log Analytics is deployed in'
    type: string
    required: true
  - id: logAnalyticsWorkspace
    name: Log Analytics Workspace
    description: 'The Resource name for an existing Log Analytics Workspaces'
    type: string
    required: true
  - id: cosmosDBResourceGroup
    name: Resource Group for CosmosDB
    description: 'The Resource Group the existing CosmosDB is deployed in'
    type: string
    required: true
  - id: cosmosDBName
    name: Log Analytics Workspace
    description: 'The Resource name for an existing Cosmos Database'
    type: string
    required: true