trigger:
  branches:
    include:
    - main
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: adecosmosapp2_build
  variables:
  - name: solutionPath
    value: $(Build.SourcesDirectory)//
  jobs:
  - job: Publish_infrastructure
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact infrastructure '
      inputs:
        targetPath: infrastructure
        artifact: infrastructure
        properties: ''
  - job: Publish_tests
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact tests '
      inputs:
        targetPath: tests
        artifact: tests
        properties: ''
  - job: whatif_adecosmosapp2_dev2_eus
    steps:
    - task: AzureCLI@2
      displayName: validate bicep
      inputs:
        azureSubscription: AzureDevExtServiceConnection
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment group validate --resource-group <ResourceGroupName> --name azureADOCLIDeployment --template-file infrastructure/main.bicep --parameters infrastructure/parameters/dev2.eus.parameters.json '
    - task: AzureCLI@2
      displayName: what-if bicep
      inputs:
        azureSubscription: AzureDevExtServiceConnection
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: az deployment group what-if --resource-group <ResourceGroupName> --name azureADOCLIDeployment --template-file infrastructure/main.bicep --parameters infrastructure/parameters/dev2.eus.parameters.json --out yamlc
  - job: build_publish_todo
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK v
      inputs:
        packageType: 'sdk'
        version: ''
        includePreviewVersions: true
    - task: NuGetAuthenticate@0
      displayName: 'NuGet Authenticate'
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: $(Build.SourcesDirectory)/src/todo/**/*.csproj
        arguments: --configuration Release
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(Build.SourcesDirectory)/src/todo/**/*.csproj
        arguments: '--configuration Release --output drop/todo '
        zipAfterPublish: true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact todo '
      inputs:
        targetPath: drop/todo
        artifact: todo
        properties: ''
- stage: adecosmosapp2_ade_build
  jobs:
  - job: adecosmosapp2_eus_create_ade
    dependsOn: []
    steps:
    - task: AzureCLI@2
      displayName: Deploy ADE Environment
      inputs:
        azureSubscription: AzureDevExtServiceConnection
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter dev environment create --dev-center-name <DevCenterName> --project-name <DevCenterProjectName> --catalog-name <DevCenterCatalogName> --environment-definition-name <EnvironmentDefinitionName> --environment-type <DevCenterProjectEnvironmentTypeName> --name <DeploymentEnvironmentInstanceToCreateName> --parameters infrastructure/parameters/ade.eus.parameters.json '
  - deployment: adecosmosapp2_app_cicd_eus
    environment:
      name: cicd
    dependsOn:
    - adecosmosapp2_eus_create_ade
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: <AzureServiceConnectionName>
              appType: webAppLinux
              WebAppName: <WebAppNameCreatedByADE>
              packageForLinux: $(Pipeline.Workspace)/todo/*.zip
  - deployment: run_azure_load_test_cicd_eus
    environment:
      name: cicd_loadtest
    dependsOn:
    - adecosmosapp2_app_cicd_eus
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureLoadTest@1
            inputs:
              azureSubscription: <AzureServiceConnectionName>
              loadTestConfigFile: $(Pipeline.Workspace)/tests/SampleApp.yaml
              resourceGroup: <LoadTestingResourceGroupName>
              loadTestResource: <LoadTestingResourceName>
              secretsJSONObject: ''
              secrets: ''
              env: ' [ { "name": "webapp", "value": "<FullURLOfADEWebApp>" } ]'
  - job: adecosmosapp2_eus_delete_ade
    dependsOn:
    - run_azure_load_test_cicd_eus
    condition: always()
    steps:
    - task: AzureCLI@2
      displayName: Destroy ADE Environment
      inputs:
        azureSubscription: <AzureServiceConnectionName>
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az devcenter dev environment delete --dev-center <DevCenterName> --project-name <DevCenterProjectName> --name <DeploymentEnvironmentInstanceToCreateName> --yes  '

  variables:
  - name: dependsOnEnv
    value: adecosmosapp2_ade_build
  - name: workSpace
    value: $(Pipeline.Workspace)
  dependsOn:
  - adecosmosapp2_ade_build
  jobs:
  - deployment: adecosmosapp2_infrastructure_dev2_eus
    environment:
      name: dev2
    dependsOn: []
    variables:
    - name: azureServiceConnectionName
      value: 'AzureDevExtServiceConnection'
    - name: azureSubscriptionID
      value: '898e66c4-4550-43c4-93a1-2d3c16932df2'
    - name: functionAppAbrv
      value: 'fn'
    - name: resourceGroupAbrv
      value: 'rg'
    - name: apiManagerAbrv
      value: 'apim'
    - name: apiAbrv
      value: 'api'
    - name: keyVaultAbrv
      value: 'kv'
    - name: sqlServerAbrv
      value: 'sql'
    - name: sqlServerURLSuffix
      value: '.database.windows.net'
    - name: sqlDBAbrv
      value: 'sqldb'
    - name: webAppAbrv
      value: 'app'
    - name: dataFactoryAbrv
      value: 'adf'
    - name: storageAccountAbrv
      value: 'sa'
    - name: deploymentName
      value: adecosmosapp2_infrastructure_dev2_eus
    - name: resourceGroupName
      value: -adecosmosapp2-dev2-eus
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: what-if bicep
            inputs:
              azureSubscription: AzureDevExtServiceConnection
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: az deployment group what-if --resource-group rg-adecosmosapp2-dev2-eus --name adecosmosapp2_infrastructure_dev2_eus --template-file $(Pipeline.Workspace)/infrastructure/main.bicep --parameters $(Pipeline.Workspace)/infrastructure/parameters/dev2.eus.parameters.json --out yamlc
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: Resource Group
              azureResourceManagerConnection: AzureDevExtServiceConnection
              action: Create Or Update Resource Group
              resourceGroupName: rg-adecosmosapp2-dev2-eus
              location: eastus
              csmFile: $(Agent.BuildDirectory)/infrastructure/main.bicep
              csmParametersFile: $(Agent.BuildDirectory)/infrastructure/parameters/dev2.eus.parameters.json
              overrideParameters: ''
              deploymentMode: Incremental
  - deployment: adecosmosapp2_app_dev2_eus
    environment:
      name: dev2
    dependsOn:
    - adecosmosapp2_infrastructure_dev2_eus
    variables:
    - name: azureServiceConnectionName
      value: 'AzureDevExtServiceConnection'
    - name: azureSubscriptionID
      value: '898e66c4-4550-43c4-93a1-2d3c16932df2'
    - name: functionAppAbrv
      value: 'fn'
    - name: resourceGroupAbrv
      value: 'rg'
    - name: apiManagerAbrv
      value: 'apim'
    - name: apiAbrv
      value: 'api'
    - name: keyVaultAbrv
      value: 'kv'
    - name: sqlServerAbrv
      value: 'sql'
    - name: sqlServerURLSuffix
      value: '.database.windows.net'
    - name: sqlDBAbrv
      value: 'sqldb'
    - name: webAppAbrv
      value: 'app'
    - name: dataFactoryAbrv
      value: 'adf'
    - name: storageAccountAbrv
      value: 'sa'
    - name: deploymentName
      value: adecosmosapp2_app_deploy_dev2_eus
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: AzureDevExtServiceConnection
              appType: webAppLinux
              WebAppName: app-adecosmosapp2-dev2-eus
              packageForLinux: $(Pipeline.Workspace)/todo/*.zip

