parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      regionAbrvs: ['eus']
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'adecosmosapp2'
- name: adeObjects
  type: object
  default:
    - devCenterName: 'dc-poc-dev-eus'
      projectName: 'webappdev'
      catalogName: 'demo_app'
      environmentDefinitionName: 'DemoApp'
      environmentType: 'CICD'
      regionAbrvs: ['eus']
- name: projectNamesConfigurations
  type: object
  default:
    - projectName: 'todo'
      publishWebProject: true
      dotnetTest: false
- name: deploymentScope
  type: string
  default: 'resourceGroup'
- name: webAppType
  type: string
  default: 'webAppLinux'
- name: artifactsToPublish
  type: object
  default: ['infrastructure','tests']


stages:
- template: stages/bicep_dotnet_build_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    templateFileName: ${{ parameters.templateFileName }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }}
    projectNamesConfigurations: ${{ parameters.projectNamesConfigurations }}
    deploymentScope: ${{ parameters.deploymentScope }}
    artifactsToPublish: ${{ parameters.artifactsToPublish }}
    
 
- template: stages/ade_loadtest_stage.yml@templates
  parameters:
    adeObjects: ${{ parameters.adeObjects }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }} 
    loadTestConfigFile: 'tests/SampleApp.yaml'
    envJSONObject: '
        [
          {
          "name": "webapp",
          "value": "$(webAppName).azurewebsites.net"
          }
        ]'
    loadTestResourceName: 'lt-test-dev-eus'
    loadTestResourceGroupName: 'rg-test-dev-eus'
    environmentName: 'cicd'
      
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/bicep_app_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
      templateDirectory: ${{ parameters.templateDirectory }}
      deploymentScope: ${{ parameters.deploymentScope }}
      webAppType: ${{ parameters.webAppType}}
      packageForLinux: '$(Pipeline.Workspace)/todo/*.zip'
