resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/deploymentEnvironments
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ../variables/azure_global_variables.yml@templates

stages:
    - template: demo_environment_template.yml