parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      regionAbrvs: ['eus']
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'infrastructure/terraform'
- name: serviceName
  type: string
  default: 'adecosmosapp2tf'
- name: adeObjects
  type: object
  default:
    - devCenterName: 'dc-poc-dev-eus'
      projectName: 'webappdev'
      catalogName: 'demo_app'
      environmentDefinitionName: 'DemoAppTF'
      environmentType: 'CICD'
      regionAbrvs: ['eus']
- name: projectNamesConfigurations
  type: object
  default:
    - projectName: 'todo'
      publishWebProject: true
      dotnetTest: false
- name: deploymentScope
  type: string
  default: 'resourceGroup'
- name: webAppType
  type: string
  default: 'webAppLinux'
- name: artifactsToPublish
  type: object
  default: ['infrastructure','tests']
- name: loadTestResourceGroupName
  type: string
  default: 'rg-loadtesting-dev-eus'
- name: loadTestResourceName
  type: string
  default: 'lt-loadtesting-dev-eus'
- name: packageForLinux
  type: string
  default: '$(Pipeline.Workspace)/todo/*.zip'
- name: runADE
  type: boolean
  default: true


stages:
- template: stages/bicep_dotnet_build_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    templateFileName: ${{ parameters.templateFileName }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }}
    projectNamesConfigurations: ${{ parameters.projectNamesConfigurations }}
    deploymentScope: ${{ parameters.deploymentScope }}
    artifactsToPublish: ${{ parameters.artifactsToPublish }}
    
- ${{ if eq(parameters.runADE, true)}}:
  - template: stages/ade_loadtest_stage.yml@templates
    parameters:
      adeObjects: ${{ parameters.adeObjects }}
      serviceName: ${{ parameters.serviceName }}
      templateDirectory: ${{ parameters.templateDirectory }} 
      loadTestConfigFile: 'tests/SampleApp.yaml'
      envJSONObject: '
          [
            {
            "name": "webapp",
            "value": "app-adecosmosapp2-cicd-eus.azurewebsites.net"
            }
          ]'
      loadTestResourceName: ${{ parameters.loadTestResourceName }}
      loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
      environmentName: 'cicd'
      webAppType: ${{ parameters.webAppType}}
      packageForLinux: ${{ parameters.packageForLinux}}
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/bicep_app_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
      templateDirectory: ${{ parameters.templateDirectory }}
      deploymentScope: ${{ parameters.deploymentScope }}
      webAppType: ${{ parameters.webAppType}}
      packageForLinux: ${{ parameters.packageForLinux}}
      runADE: ${{ parameters.runADE}}
