parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev2'
      regionAbrvs: ['eus']
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'adecosmosapp'
- name: adeObjects
  type: object
  default:
    - devCenterName: 'dc-poc-dev-eus'
      projectName: 'webappdev'
      catalogName: 'demo_app'
      environmentDefinitionName: 'DemoApp'
      environmentType: 'CICD'
      regionAbrvs: ['eus']
          

stages:
- template: stages/bicep_build_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    templateFileName: ${{ parameters.templateFileName }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }}
- template: stages/ade_loadtest_stage.yml@templates
  parameters:
    adeObjects: ${{ parameters.adeObjects }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }} 
    loadTestConfigFile: 'tests/SampleApp.yaml'
    serviceName: ${{ parameters.serviceName }}
    envJSONObject: '
        [
          {
          "name": "webapp",
          "value": "$(webAppName).azurewebsites.net"
          }
        ]'
    loadTestResourceName: 'lt-test-dev-eus'
    loadTestResourceGroupName: 'rg-test-dev-eus'
    
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/bicep_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
